stages:
- lint

.secure_files: &secure_files_downloading
  - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/load-secure-files/-/raw/main/installer | bash

lint:
 stage: lint
 artifacts:
   paths:
     - reports/
   expire_in: 1 week
 image: python:3.10
 before_script:
 - curl -sSL https://install.python-poetry.org | python3 -
 - export PATH="/root/.local/bin:$PATH"
 - poetry config virtualenvs.create false
 - poetry config http-basic.gitlab $CI_REGISTRY_USER $CI_JOB_TOKEN
 - poetry install
 script:
   - make lint
